remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Computer Vision and AI

description: Learn AI and Computer Vision step by step and practically
author:
  name: Shiva Omidzadeh
  email: Shiva.Omidzadeh@outlook.com
  github: Shivaomzd
  twitter: anidotnet
  #pinterest: asd123
  linkedin: Shiva Omidzadeh
  bio: blog of Shiva Omidzadeh!
  #email_md5: 9c74f9c66df98052bef13864bffcd09c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
